version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: 'wilsonid-build-{{ .Branch }}-{{ .Revision }}'
          paths:
            - ./
  
  deploy-prod:
    docker:
      - image: circleci/node:12.14
    environment:
      AWS_REGION: us-west-2
    steps:
      - restore_cache:
          key: "wilsonid-build-{{ .Branch }}-{{ .Revision }}"
      - run:
          command: npm run deploy
          no_output_timeout: "1h"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master